/**
 * blog-loader.ts
 *
 * Unified data layer for blog content — static-file-only implementation.
 *
 * All data is served from /blog-data.json (generated at build time).
 * This works identically in local dev, Replit, and GitHub Pages / CDN.
 *
 * The static file is generated by `node scripts/generate-blog-static.mjs`
 * and is automatically regenerated on every server start via the
 * blogStaticDataPlugin Vite plugin.
 */

// ─── Types ────────────────────────────────────────────────────────────────────

export interface BlogPost {
  id: string;
  slug: string;
  title: string;
  excerpt: string;
  content: string;
  coverImage?: string | null;
  author: string;
  category: string;
  tags: string[];
  publishedAt: string;
  readingTimeMinutes: number;
  featured: boolean;
  status: string;
  difficulty?: string | null;
}

export interface BlogCategory {
  id: string;
  name: string;
  slug: string;
}

interface StaticBlogData {
  posts: BlogPost[];
  categories: BlogCategory[];
  tags: string[];
}

// ─── Static data loader ───────────────────────────────────────────────────────

let _staticData: StaticBlogData | null = null;

async function loadStaticData(): Promise<StaticBlogData> {
  if (_staticData) return _staticData;
  const res = await fetch('/blog-data.json');
  if (!res.ok) throw new Error(`Failed to load static blog data: ${res.status}`);
  _staticData = await res.json() as StaticBlogData;
  return _staticData;
}

// ─── Public API ───────────────────────────────────────────────────────────────

export async function getFeaturedPosts(limit = 3): Promise<BlogPost[]> {
  const data = await loadStaticData();
  const featured = data.posts.filter((p) => p.featured);
  return (featured.length > 0 ? featured : data.posts).slice(0, limit);
}

export async function getPosts({
  limit = 12,
  page = 1,
  category,
  tag,
}: {
  limit?: number;
  page?: number;
  category?: string;
  tag?: string;
} = {}): Promise<{ data: BlogPost[]; meta: { total: number; page: number; pageSize: number; totalPages: number } }> {
  const data = await loadStaticData();
  let filtered = data.posts;

  if (category) {
    filtered = filtered.filter((p) => p.category.toLowerCase() === category.toLowerCase());
  }
  if (tag) {
    filtered = filtered.filter((p) => p.tags.some((t) => t.toLowerCase() === tag.toLowerCase()));
  }

  const total = filtered.length;
  const totalPages = Math.ceil(total / limit);
  const start = (page - 1) * limit;
  return {
    data: filtered.slice(start, start + limit),
    meta: { total, page, pageSize: limit, totalPages },
  };
}

export async function getCategories(): Promise<BlogCategory[]> {
  const data = await loadStaticData();
  return data.categories;
}

export async function getTags(): Promise<string[]> {
  const data = await loadStaticData();
  return data.tags;
}

export async function searchPosts(query: string): Promise<BlogPost[]> {
  const data = await loadStaticData();
  const q = query.toLowerCase();
  return data.posts
    .filter(
      (p) =>
        p.title.toLowerCase().includes(q) ||
        p.excerpt.toLowerCase().includes(q) ||
        p.tags.some((t) => t.toLowerCase().includes(q)) ||
        p.category.toLowerCase().includes(q)
    )
    .slice(0, 20);
}

export async function getPostWithContext(slug: string): Promise<{
  data: BlogPost;
  related: BlogPost[];
  prev: BlogPost | null;
  next: BlogPost | null;
} | null> {
  const data = await loadStaticData();
  const idx = data.posts.findIndex((p) => p.slug === slug);
  if (idx === -1) return null;

  const post = data.posts[idx];

  const related = data.posts
    .filter(
      (p, i) =>
        i !== idx &&
        (p.category === post.category || p.tags.some((t) => post.tags.includes(t)))
    )
    .slice(0, 3);

  const prev = idx > 0 ? data.posts[idx - 1] : null;
  const next = idx < data.posts.length - 1 ? data.posts[idx + 1] : null;

  return { data: post, related, prev, next };
}
