/**
 * blog-loader.ts
 *
 * Unified data layer for blog content.
 *
 * Strategy:
 *  1. Try the Express REST API (/api/blog/*)  — works in dev and when deployed with a backend
 *  2. Fall back to /blog-data.json            — pre-built static file for GitHub Pages / CDN
 *
 * The static file is generated by `node scripts/generate-blog-static.mjs`
 * and is automatically regenerated on every Vite build via the blogStaticDataPlugin.
 */

// ─── Types ────────────────────────────────────────────────────────────────────

export interface BlogPost {
  id: string;
  slug: string;
  title: string;
  excerpt: string;
  content: string;
  coverImage?: string | null;
  author: string;
  category: string;
  tags: string[];
  publishedAt: string;
  readingTimeMinutes: number;
  featured: boolean;
  status: string;
  difficulty?: string | null;
}

export interface BlogCategory {
  id: string;
  name: string;
  slug: string;
}

interface StaticBlogData {
  posts: BlogPost[];
  categories: BlogCategory[];
  tags: string[];
}

// ─── API availability check ───────────────────────────────────────────────────

let _apiAvailable: boolean | null = null;

async function isApiAvailable(): Promise<boolean> {
  if (_apiAvailable !== null) return _apiAvailable;
  try {
    const res = await fetch('/api/blog/health', { signal: AbortSignal.timeout(3000) });
    _apiAvailable = res.ok;
  } catch {
    _apiAvailable = false;
  }
  return _apiAvailable;
}

// ─── Static data loader ───────────────────────────────────────────────────────

let _staticData: StaticBlogData | null = null;

async function loadStaticData(): Promise<StaticBlogData> {
  if (_staticData) return _staticData;
  const res = await fetch('/blog-data.json');
  if (!res.ok) throw new Error(`Failed to load static blog data: ${res.status}`);
  _staticData = await res.json() as StaticBlogData;
  return _staticData;
}

// ─── Public API ───────────────────────────────────────────────────────────────

export async function getFeaturedPosts(limit = 3): Promise<BlogPost[]> {
  if (await isApiAvailable()) {
    const res = await fetch(`/api/blog/posts/featured?limit=${limit}`);
    if (res.ok) {
      const json = await res.json();
      return json.data ?? [];
    }
  }
  const data = await loadStaticData();
  return data.posts.filter((p) => p.featured).slice(0, limit);
}

export async function getPosts({
  limit = 12,
  page = 1,
  category,
  tag,
}: {
  limit?: number;
  page?: number;
  category?: string;
  tag?: string;
} = {}): Promise<{ data: BlogPost[]; meta: { total: number; page: number; pageSize: number; totalPages: number } }> {
  if (await isApiAvailable()) {
    const params = new URLSearchParams({ limit: String(limit), page: String(page) });
    if (category) params.set('category', category);
    if (tag) params.set('tag', tag);
    const res = await fetch(`/api/blog/posts?${params}`);
    if (res.ok) return res.json();
  }

  // Static fallback
  const data = await loadStaticData();
  let filtered = data.posts;
  if (category) {
    filtered = filtered.filter((p) => p.category.toLowerCase() === category.toLowerCase());
  }
  if (tag) {
    filtered = filtered.filter((p) => p.tags.some((t) => t.toLowerCase() === tag.toLowerCase()));
  }
  const total = filtered.length;
  const totalPages = Math.ceil(total / limit);
  const start = (page - 1) * limit;
  return {
    data: filtered.slice(start, start + limit),
    meta: { total, page, pageSize: limit, totalPages },
  };
}

export async function getCategories(): Promise<BlogCategory[]> {
  if (await isApiAvailable()) {
    const res = await fetch('/api/blog/categories');
    if (res.ok) {
      const json = await res.json();
      return json.data ?? [];
    }
  }
  const data = await loadStaticData();
  return data.categories;
}

export async function getTags(): Promise<string[]> {
  if (await isApiAvailable()) {
    const res = await fetch('/api/blog/tags');
    if (res.ok) {
      const json = await res.json();
      return json.data ?? [];
    }
  }
  const data = await loadStaticData();
  return data.tags;
}

export async function searchPosts(query: string): Promise<BlogPost[]> {
  if (await isApiAvailable()) {
    const res = await fetch(`/api/blog/search?q=${encodeURIComponent(query)}`);
    if (res.ok) {
      const json = await res.json();
      return json.data ?? [];
    }
  }
  const data = await loadStaticData();
  const q = query.toLowerCase();
  return data.posts
    .filter(
      (p) =>
        p.title.toLowerCase().includes(q) ||
        p.excerpt.toLowerCase().includes(q) ||
        p.tags.some((t) => t.toLowerCase().includes(q)) ||
        p.category.toLowerCase().includes(q)
    )
    .slice(0, 20);
}

export async function getPostWithContext(slug: string): Promise<{
  data: BlogPost;
  related: BlogPost[];
  prev: BlogPost | null;
  next: BlogPost | null;
} | null> {
  if (await isApiAvailable()) {
    const res = await fetch(`/api/blog/posts/${encodeURIComponent(slug)}`);
    if (res.ok) return res.json();
  }

  // Static fallback
  const data = await loadStaticData();
  const idx = data.posts.findIndex((p) => p.slug === slug);
  if (idx === -1) return null;

  const post = data.posts[idx];

  const related = data.posts
    .filter(
      (p, i) =>
        i !== idx &&
        (p.category === post.category || p.tags.some((t) => post.tags.includes(t)))
    )
    .slice(0, 3);

  const prev = idx > 0 ? data.posts[idx - 1] : null;
  const next = idx < data.posts.length - 1 ? data.posts[idx + 1] : null;

  return { data: post, related, prev, next };
}
