# Funding links for Code Reels
# These are displayed in the "Sponsor" button on GitHub

github: [satishkumar-dhule]
# patreon: codereels
# open_collective: code-reels
# ko_fi: codereels
# custom: ["https://www.buymeacoffee.com/codereels"]
